name: Auto-Tag

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  pull_request:
    types: [ "closed" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  update_tag:
    if: >-
      github.event.pull_request.merged == true &&
      contains(github.event.pull_request.labels.*.name, 'renovate_publish')

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: jaliborc/action-general-autotag@1.0.0
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          source_file: "Dockerfile"
          extraction_regex: "HCLOUD_VERSION=(v\\d+\\.\\d+\\.\\d+)"
